id: taxonomy_term.full
uuid: 0659048c-2899-40e2-9500-f1112c755dec
label: 'Taxonomy term page'
targetEntityType: taxonomy_term
status: true
cache: true
langcode: und
dependencies:
  module:
    - taxonomy
