id: node.search_result
uuid: 2354b080-0114-4be1-9206-6ffdefc4aa72
label: 'Search result highlighting input'
targetEntityType: node
status: false
cache: true
langcode: und
dependencies:
  module:
    - node
